server:
  port: 8082

spring:
  application:
    name: springcloud-provider
  datasource:
    url: jdbc:mysql://localhost:3306/seven?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
